export type TxType = "Payment" | "Escrow" | "Wallet" | "Refund"
export type TxStatus = "Completed" | "Pending" | "In Escrow" | "Failed" | "Refunded"
export type TxMethod = "Bank Transfer" | "Credit Card" | "Wallet Balance" | "ACH" | "Wire"
export type TxDirection = "in" | "out"

export interface Transaction {
  id: string
  date: string // ISO for sorting
  displayDate: string
  type: TxType
  description: string
  counterparty: string
  dealId?: string
  method: TxMethod
  status: TxStatus
  direction: TxDirection
  amount: number
  fee: number
  reference: string
  // type-specific details
  escrowReleaseDate?: string
  walletBalanceAfter?: number
  refundReason?: string
  originalTxId?: string
}

export const TX_TYPES: TxType[] = ["Payment", "Escrow", "Wallet", "Refund"]
export const TX_STATUSES: TxStatus[] = [
  "Completed",
  "Pending",
  "In Escrow",
  "Failed",
  "Refunded",
]
export const TX_METHODS: TxMethod[] = [
  "Bank Transfer",
  "Credit Card",
  "Wallet Balance",
  "ACH",
  "Wire",
]

export const TRANSACTIONS: Transaction[] = [
  {
    id: "TXN-58210",
    date: "2026-07-09",
    displayDate: "Jul 09, 2026",
    type: "Payment",
    description: "Milestone 2 — Payments module",
    counterparty: "Nova Labs",
    dealId: "DL-1031",
    method: "Wallet Balance",
    status: "In Escrow",
    direction: "out",
    amount: 12000,
    fee: 60,
    reference: "REF-NL-0231",
    escrowReleaseDate: "Jul 20, 2026",
  },
  {
    id: "TXN-58194",
    date: "2026-07-08",
    displayDate: "Jul 08, 2026",
    type: "Escrow",
    description: "Kick-off deposit funded",
    counterparty: "Apex Studios",
    dealId: "DL-1042",
    method: "Bank Transfer",
    status: "In Escrow",
    direction: "out",
    amount: 5000,
    fee: 25,
    reference: "REF-AS-1180",
    escrowReleaseDate: "Jul 22, 2026",
  },
  {
    id: "TXN-58177",
    date: "2026-07-07",
    displayDate: "Jul 07, 2026",
    type: "Wallet",
    description: "Deposit from linked account",
    counterparty: "Chase ****8890",
    method: "ACH",
    status: "Completed",
    direction: "in",
    amount: 15000,
    fee: 0,
    reference: "REF-DEP-4021",
    walletBalanceAfter: 48250,
  },
  {
    id: "TXN-58150",
    date: "2026-07-05",
    displayDate: "Jul 05, 2026",
    type: "Payment",
    description: "Full payment — Logo & Branding",
    counterparty: "Pixel Forge",
    dealId: "DL-1024",
    method: "Wallet Balance",
    status: "Completed",
    direction: "out",
    amount: 3200,
    fee: 16,
    reference: "REF-PF-0092",
  },
  {
    id: "TXN-58142",
    date: "2026-07-05",
    displayDate: "Jul 05, 2026",
    type: "Refund",
    description: "Partial refund — scope adjustment",
    counterparty: "RankUp Co.",
    dealId: "DL-1018",
    method: "Wallet Balance",
    status: "Refunded",
    direction: "in",
    amount: 400,
    fee: 0,
    reference: "REF-RC-0451",
    refundReason: "Deliverables did not meet the agreed scope for Month 2.",
    originalTxId: "TXN-57980",
  },
  {
    id: "TXN-58110",
    date: "2026-07-03",
    displayDate: "Jul 03, 2026",
    type: "Payment",
    description: "Phase 1 — Discovery",
    counterparty: "Northwind Advisory",
    dealId: "DL-1009",
    method: "Wire",
    status: "Completed",
    direction: "out",
    amount: 7500,
    fee: 45,
    reference: "REF-NA-0771",
  },
  {
    id: "TXN-58098",
    date: "2026-07-02",
    displayDate: "Jul 02, 2026",
    type: "Escrow",
    description: "Milestone 1 — Auth released",
    counterparty: "Nova Labs",
    dealId: "DL-1031",
    method: "Wallet Balance",
    status: "Completed",
    direction: "out",
    amount: 10000,
    fee: 50,
    reference: "REF-NL-0198",
  },
  {
    id: "TXN-58061",
    date: "2026-07-01",
    displayDate: "Jul 01, 2026",
    type: "Wallet",
    description: "Withdrawal to bank",
    counterparty: "Chase ****8890",
    method: "ACH",
    status: "Pending",
    direction: "out",
    amount: 5000,
    fee: 0,
    reference: "REF-WD-3390",
    walletBalanceAfter: 33250,
  },
  {
    id: "TXN-58044",
    date: "2026-06-29",
    displayDate: "Jun 29, 2026",
    type: "Payment",
    description: "Setup fee — Q3 Ad Campaign",
    counterparty: "BrightMedia",
    dealId: "DL-1039",
    method: "Credit Card",
    status: "Failed",
    direction: "out",
    amount: 2000,
    fee: 0,
    reference: "REF-BM-0510",
  },
  {
    id: "TXN-58021",
    date: "2026-06-28",
    displayDate: "Jun 28, 2026",
    type: "Wallet",
    description: "Deposit from linked account",
    counterparty: "Amex ****3007",
    method: "Credit Card",
    status: "Completed",
    direction: "in",
    amount: 20000,
    fee: 120,
    reference: "REF-DEP-3890",
    walletBalanceAfter: 38250,
  },
  {
    id: "TXN-57998",
    date: "2026-06-26",
    displayDate: "Jun 26, 2026",
    type: "Escrow",
    description: "Month 1 released — SEO Retainer",
    counterparty: "RankUp Co.",
    dealId: "DL-1018",
    method: "Wallet Balance",
    status: "Completed",
    direction: "out",
    amount: 800,
    fee: 4,
    reference: "REF-RC-0388",
  },
  {
    id: "TXN-57980",
    date: "2026-06-24",
    displayDate: "Jun 24, 2026",
    type: "Payment",
    description: "Month 2 — SEO Retainer",
    counterparty: "RankUp Co.",
    dealId: "DL-1018",
    method: "Wallet Balance",
    status: "Completed",
    direction: "out",
    amount: 800,
    fee: 4,
    reference: "REF-RC-0402",
  },
  {
    id: "TXN-57944",
    date: "2026-06-22",
    displayDate: "Jun 22, 2026",
    type: "Refund",
    description: "Full refund — cancelled order",
    counterparty: "Loop Interactive",
    method: "Credit Card",
    status: "Refunded",
    direction: "in",
    amount: 1500,
    fee: 0,
    reference: "REF-LI-0033",
    refundReason: "Order cancelled before work commenced. Full amount returned.",
    originalTxId: "TXN-57900",
  },
  {
    id: "TXN-57921",
    date: "2026-06-20",
    displayDate: "Jun 20, 2026",
    type: "Wallet",
    description: "Deposit from linked account",
    counterparty: "Chase ****8890",
    method: "Bank Transfer",
    status: "Completed",
    direction: "in",
    amount: 10000,
    fee: 0,
    reference: "REF-DEP-3701",
    walletBalanceAfter: 18250,
  },
  {
    id: "TXN-57900",
    date: "2026-06-18",
    displayDate: "Jun 18, 2026",
    type: "Payment",
    description: "Initial payment — Loop Interactive",
    counterparty: "Loop Interactive",
    method: "Credit Card",
    status: "Refunded",
    direction: "out",
    amount: 1500,
    fee: 8,
    reference: "REF-LI-0021",
  },
  {
    id: "TXN-57882",
    date: "2026-06-16",
    displayDate: "Jun 16, 2026",
    type: "Payment",
    description: "Consulting deposit",
    counterparty: "Meridian Group",
    method: "Wire",
    status: "Pending",
    direction: "out",
    amount: 6000,
    fee: 36,
    reference: "REF-MG-0140",
  },
  {
    id: "TXN-57855",
    date: "2026-06-14",
    displayDate: "Jun 14, 2026",
    type: "Escrow",
    description: "Design approval milestone funded",
    counterparty: "Apex Studios",
    dealId: "DL-1042",
    method: "Bank Transfer",
    status: "In Escrow",
    direction: "out",
    amount: 4000,
    fee: 20,
    reference: "REF-AS-1090",
    escrowReleaseDate: "Jul 22, 2026",
  },
  {
    id: "TXN-57830",
    date: "2026-06-12",
    displayDate: "Jun 12, 2026",
    type: "Wallet",
    description: "Withdrawal to bank",
    counterparty: "Chase ****8890",
    method: "ACH",
    status: "Completed",
    direction: "out",
    amount: 2500,
    fee: 0,
    reference: "REF-WD-3120",
    walletBalanceAfter: 8250,
  },
]

export const STATUS_STYLES: Record<TxStatus, string> = {
  Completed: "bg-green-500/10 text-green-600 border-transparent hover:bg-green-500/10",
  Pending: "bg-amber-500/10 text-amber-600 border-transparent hover:bg-amber-500/10",
  "In Escrow": "bg-blue-500/10 text-blue-600 border-transparent hover:bg-blue-500/10",
  Failed: "bg-destructive/10 text-destructive border-transparent hover:bg-destructive/10",
  Refunded: "bg-purple-500/10 text-purple-600 border-transparent hover:bg-purple-500/10",
}

export function formatCurrency(amount: number): string {
  return amount.toLocaleString("en-US", {
    style: "currency",
    currency: "USD",
    minimumFractionDigits: 2,
  })
}

export function signedAmount(tx: Transaction): string {
  const sign = tx.direction === "in" ? "+" : "-"
  return `${sign}${formatCurrency(tx.amount)}`
}
